Third time's a charm

diff --git a/.github/workflows/presto-test-composite.yml b/.github/workflows/presto-test-composite.yml
--- a/.github/workflows/presto-test-composite.yml
+++ b/.github/workflows/presto-test-composite.yml
@@ -76,10 +76,12 @@ jobs:
           ./start_${{ inputs.presto_worker_type }}_presto.sh
           popd
       - name: Run Integration Tests
+        # avoid Q15 on GPU as it will fail output comparison until the schema differences are resolved
+        env:
+          Q_OPTION: ${{ inputs.presto_worker_type == 'gpu' && echo '-q 1,2,3,4,5,6,7,8,9,10,11,12,13,14,16,17,18,19,20,21,22' || echo '' }}
         run: |
           pushd velox-testing/presto/scripts
-          # avoid Q15 on GPU as it will fail output comparison until the schema differences are resolved
-          ./run_integ_test.sh -b tpch ${{ inputs.presto_worker_type == 'gpu' && echo '-q 1,2,3,4,5,6,7,8,9,10,11,12,13,14,16,17,18,19,20,21,22' || echo '' }}
+          ./run_integ_test.sh -b tpch ${{ env.Q_OPTION }}
           popd
       - name: Shutdown Presto
         run: |
